### ISSUE TITLE
EMA model not working

### ISSUE THREAD

**Issue by Caspeerrr** [happyharrycn/actionformer_release#103]
I use the default configurations etc on  a custom dataset and I didn't change anything in the code. However, during evaluation the map score is very low (10 %)

When I change:
model.load_state_dict(checkpoint['state_dict_ema'])
to:
model.load_state_dict(checkpoint['state_dict'])

the map score is a lot higher (~40%). Why isn't the EMA model working? 
thank you!

**Comment by happyharrycn** [comment]
To get the EMA model working, you will need to train the model for many iterations, so that the learned weights can be aggregated into the EMA model. If you have a short training schedule (# epochs) or a small dataset (# mini batch per epoch), the number of iterations might not be sufficient. If an early stopping is strongly preferred (usually due to a small dataset), EMA should be turned off.

**Comment by happyharrycn** [comment]
Closed due to inactivity.
