### ISSUE TITLE
make gt(.json) consistent with feature extracted by action model(eg, I3D)

### ISSUE THREAD

**Issue by dulibubai** [happyharrycn/actionformer_release#12]
when doing sample with images from video, how to generate gt json consistent with feature extracted by action model(eg, I3D)?
look forward to your reply? Do you have same code for us inference? Thanks very much!

**Comment by happyharrycn** [comment]
The json file stores the video information and action annotations of a dataset, and is mostly irrelevant of how frames are sampled from videos. This is because action annotations are stored in absolute timestamps (seconds) in the json file, and thus are independent of how the video features are extracted.

When using different video features, you will need to specify how the features are extracted in the yaml config file (e.g., _thumos_i3d.yaml_). The parameters are under _dataset_ and include

- feat_stride: Temporal stride of the local sliding window for feature extraction.
- num_frames: Number of frames within each local window 
- default_fps: Default FPS for all videos. If not specified, FPS will be derived from video information stored in the json file (not recommended). 

You might want to refer to #4 for an illustration of these parameters.

**Comment by dulibubai** [comment]
Thanks very much!

**Comment by happyharrycn** [comment]
Mark as resolved.
