### ISSUE TITLE
multi-class nms

### ISSUE THREAD

**Issue by Darknesszlx** [happyharrycn/actionformer_release#15]
After training on my own dataset, I found the result after mulit-class nms is confusing! For example, segment1 is [1s:4s] and label is 1, segment2 is [2s:5s] and label is 2, so the label of segment [2s:4s] is confusing! 
Two objects' IOU is very high, but they belong to different labels, so nms do not filter one of them. In object detection it's a normal situation, but in video processing I don't know how to deal with it!  Maybe multi-nms is not appropriate?
Can you give me a little advice? Thanks a lot!

**Comment by tzzcl** [comment]
Hi, I am not sure that I fully understand your questions. 

But our code provides a simple choice to enable/disable multi-class nms, you may refer to [L47-L50](https://github.com/happyharrycn/actionformer_release/blob/main/configs/thumos_i3d.yaml#L47-L50) for instructions.

**Comment by Darknesszlx** [comment]
> Hi, I am not sure that I fully understand your questions.
> 
> But our code provides a simple choice to enable/disable multi-class nms, you may refer to [L47-L50](https://github.com/happyharrycn/actionformer_release/blob/main/configs/thumos_i3d.yaml#L47-L50) in THUMOS config for instructions.

不好意思，可能英文没表达清楚，还是直接说中文吧。
mulit-class设置成false其实也会存在这样的情况：假设两个预测的结果分别是[ 1秒-3秒，类别为1] [1秒-1.1秒，类别为2]，这两个预测结果的iou比较小, nms的iou阈值也并不能过滤掉这种情况，那最终1秒-1.1秒这个区间，类别应该怎么定呢？其实主要想问的问题就是可能存在有一段区间，但是属于两个不同的label的预测结果，应该怎么处理比较好？

**Comment by happyharrycn** [comment]
Similar to object detection, temporal action localization is a structured prediction problem, where the output is a set of temporal actions (events) rather than frame-level labels. In your example here, the output does not have any ambiguity. The model predicts an action that starts at 1s and ends at 4s with category 1, and another action that starts at 2s and ends at 5s with category 2. The segment starting at 2s and ending at 5s is not considered as an action by the model. This has nothing to do with NMS.

**Comment by happyharrycn** [comment]
Let me know if there is any further questions. Otherwise, I will mark the issue as resolved.

**Comment by happyharrycn** [comment]
Resolved due to inactivity.
