### ISSUE TITLE
loss

### ISSUE THREAD

**Issue by DD-BONED** [happyharrycn/actionformer_release#22]
你好你使用了giouloss但是在这个任务中，c和(AuB)不应该是相等的吗

**Comment by tzzcl** [comment]
你说的对，实质上GIoU Loss在1D，并且中心点为同一个的时候，会退化成IoU Loss。

**Comment by happyharrycn** [comment]
Let me know if this question is now addressed.

**Comment by DD-BONED** [comment]
但是经过我打印发现len_c - unionk有些是非0的这个怎么理解

**Comment by DD-BONED** [comment]
但是经过我打印发现len_c - unionk有些是非0的这个怎么理解

**Comment by happyharrycn** [comment]
If you print the actual values of len_c - unionk, they are either zero or very close to zero (due to limited floating point precision).

**Comment by DD-BONED** [comment]
如果咋样，为什么还是要坚持是giou呢？

**Comment by happyharrycn** [comment]
With our current implementation, GIoU is indeed equivalent to IoU. One can either call our regression loss as GIoU or IoU. This equivalence, however, can not be generalized to the temporal action localization task, and is only due to the design of our model outputs. Historically, the GIoU loss has been proven to be more effective than IoU loss for regressing action boundaries. Should our design evolves, GIoU is preferred over IoU.

**Comment by happyharrycn** [comment]
Mark as resolved.
