### ISSUE TITLE
ActivityNet I3D features

### ISSUE THREAD

**Issue by xlliu7** [happyharrycn/actionformer_release#35]
Thanks for sharing the code of the .awesome work. 
I have questions about the I3D features on ActivityNet. Are the features from [CMCS](https://github.com/Finspire13/CMCS-Temporal-Action-Localization) or extracted on your own? I found that their features from CMCS are incomplete. The features of around 400 videos on the validation set are missing, which might affect the performance evaluation.  
Thanks!

**Comment by tzzcl** [comment]
Hi, Thank you for your interest in our project. The features are from CMCS repo. 

For ActivityNet dataset, the problem is that they only release the youtube-id. Some videos are no longer accessible on Youtube. Thus it is hard to achieve absolute fair comparison on ActivityNet v1.3 dataset. Also, some method re-extracted their features using different settings with I3D. I think you may want to refer to the TSP features for a fair comparison.

**Comment by xlliu7** [comment]
Thanks for your response. My question is solved.
